#!/usr/bin/bash

# grim -g "$(slurp)" - | wl-copy
# grim -g "$(slurp)" - | swappy -f - -o ~/Pictures/Screenshots/screenshot$(date +%s).png
# grim -g "0,0 2048x1280" - | swappy -f - -o ~/Pictures/Screenshots/screenshot$(date +%s).png

geometry=`xrandr | head -n1 | cut -d',' -f2 | tr -d '[:blank:],current'`

grim -g "0,0 ${geometry}" - | swappy -f - -o ~/Pictures/Screenshots/screenshot$(date +%s).png
